"""Initial migration

Revision ID: e51f5c4d8f2a
Revises:
Create Date: 2025-03-22

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e51f5c4d8f2a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("MONITOR", "MONITOR_STATUS", "TAG", name="entitytype"),
            nullable=False,
        ),
        sa.Column(
            "change_types", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "filter_condition", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_triggers_id"), "triggers", ["id"], unique=False)

    op.create_table(
        "trigger_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trigger_id", sa.Integer(), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column(
            "change_type",
            sa.Enum("INSERT", "UPDATE", "DELETE", name="changetype"),
            nullable=False,
        ),
        sa.Column("old_data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("new_data", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["trigger_id"],
            ["triggers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trigger_events_id"), "trigger_events", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trigger_events_id"), table_name="trigger_events")
    op.drop_table("trigger_events")
    op.drop_index(op.f("ix_triggers_id"), table_name="triggers")
    op.drop_table("triggers")
    # ### end Alembic commands ###
